"""add uuid4 to all models

Revision ID: 63f4b45f1b25
Revises: 02eff888e610
Create Date: 2026-09-13 22:08:02.657941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63f4b45f1b25'
down_revision: Union[str, Sequence[str], None] = '02eff888e610'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercise',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('person_id', sa.Uuid(), nullable=True),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'BICEPs', 'TRICEPS', 'GLUTES', 'HAMSTRINGS', 'CALFS', name='musclegroupenum'), nullable=False),
    sa.Column('equipment', sa.Enum('DUMBELL', 'BARBELL', 'BODYWEIGHT', 'MACHINE', name='equipmentenum'), nullable=False),
    sa.Column('increment', sa.Float(), nullable=False),
    sa.Column('alternative1', sa.Uuid(), nullable=True),
    sa.Column('alternative2', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['alternative1'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['alternative2'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['person_id'], ['people.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('exercises')
    op.alter_column('people', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('people', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.Uuid(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sessions', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('people', 'id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.alter_column('people', 'user_id',
               existing_type=sa.Uuid(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_table('exercises',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('exercises_pkey'))
    )
    op.drop_table('exercise')
    # ### end Alembic commands ###
